"""
Features related to image recording
"""

import csv
import os
from extract import extract_image

CSV_FOLDER_PATH = "data"
IMAGE_FOLDER_PATH = "data/images/"


def download_images_from_csv(file):
    """
    read csv file and extract upc and image_url fields in order to extract and save image
    :param file: path & name
    :type file:str
    :return:
    """
    if file.endswith('.csv'):
        with open(CSV_FOLDER_PATH + "/" + file, encoding="utf-8") as fichier_csv:
            dict_reader = csv.DictReader(fichier_csv, delimiter=",")
            for row in dict_reader:
                url = row['image_url']
                file_to_download = row['upc'] + ".jpg"
                extract_image(url, IMAGE_FOLDER_PATH, file_to_download)


def images_download():
    """
    Downloads the images whose url_image is included in the csv files generated by
    the application and stores them in the data/images directory
    :return: None
    """
    if os.path.isdir(CSV_FOLDER_PATH):
        files = os.listdir(CSV_FOLDER_PATH)
        for file in files:
            download_images_from_csv(file)
